security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                # default_target_path: /aa
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator # Check the correct path to your LoginFormAuthenticator

            entry_point: App\Security\LoginFormAuthenticator # Set the appropriate entry point

            logout:
                path: app_logout
                target: app_login

    access_control:
         - { path: ^/profile, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }

# Other configurations for tests
