#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Login:
    path: /login
    controller: App\Controller\PagesController::login 
    methods: [GET, POST]

AddBandes:
    path: /addBandes
    controller: App\Controller\PagesController::ajouterBande 
    methods: [GET, POST]


listBandes:
    path: /listBandes
    controller: App\Controller\PagesController::listBandes 
    methods: [GET, POST]


index:
    path: /admin
    controller: App\Controller\PagesController::index

    

tableau:
    path: /aa
    controller: App\Controller\PagesController::listarmoire



editArmoire:
    path: /editArmoire/{id}
    controller: App\Controller\PagesController::editArmoire 
    methods: [GET, POST]
    


ajoutArmoire:
    path: /addArmoire
    controller: App\Controller\PagesController::new


deleteArmoire:
    path: /deleteArmoire/{id}
    controller: App\Controller\PagesController::deleteArmoire
    


deleteBande:
    path: /deleteBande/{id}
    controller: App\Controller\PagesController::deleteBande


editBande:
    path: /editBande/{id}
    controller: App\Controller\PagesController::editBande 
    methods: [GET, POST]
    
