#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login 
    methods: [GET, POST]

signup:
    path: /signup
    controller: App\Controller\SecurityController::signup 
    methods: [GET, POST]



showExpiredBandes:
    path: /showExpiredBandes
    controller: App\Controller\PagesController::showExpiredBandes
    methods: [GET, POST]


logintemplate:
    path: /logintemp
    controller: App\Controller\PagesController::logintemp
    methods: [GET, POST]

searchBande:
    path: /searchBande
    controller: App\Controller\PagesController::searchBande
    methods: [GET, POST]

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]



deleteUser:
    path: /deleteUser/{id}
    controller: App\Controller\RegistrationController::deleteUser
    methods: [GET, POST]

dashboard:
    path: /dashboard
    controller: App\Controller\PagesController::dashboard
    methods: [GET, POST]



cal:
    path: /cal
    controller: App\Controller\PagesController::cal
    methods: [GET, POST]

countUsers:
    path: /countUsers
    controller: App\Controller\PagesController::countUsers
    methods: [GET, POST]


editUser:
    path: /editUser/{id}
    controller: App\Controller\RegistrationController::editUser
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout 
    methods: [GET, POST]

AddBandes:
    path: /addBandes
    controller: App\Controller\PagesController::ajouterBande 
    methods: [GET, POST]

BandeExpire:
    path: /BandeExpire
    controller: App\Controller\PagesController::BandeExpire 
    methods: [GET, POST]

listBandes:
    path: /listBandes
    controller: App\Controller\PagesController::listBandes 
    methods: [GET, POST]

users:
    path: /users
    controller: App\Controller\RegistrationController::users 
    methods: [GET, POST]

index:
    path: /admin
    controller: App\Controller\PagesController::index

    

tableau:
    path: /aa
    controller: App\Controller\PagesController::listarmoire



editArmoire:
    path: /editArmoire/{id}
    controller: App\Controller\PagesController::editArmoire 
    methods: [GET, POST]
    


ajoutArmoire:
    path: /addArmoire
    controller: App\Controller\PagesController::new


deleteArmoire:
    path: /deleteArmoire/{id}
    controller: App\Controller\PagesController::deleteArmoire





deleteBande:
    path: /deleteBande/{id}
    controller: App\Controller\PagesController::deleteBande


editBande:
    path: /editBande/{id}
    controller: App\Controller\PagesController::editBande 
    methods: [GET, POST]
    
