<?php

namespace ContainerQLMY1N5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dx_TSUVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dx.TSUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dx.TSUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'armoire' => ['privates', '.errored..service_locator.Dx.TSUV.App\\Entity\\Armoire', NULL, 'Cannot autowire service ".service_locator.Dx.TSUV": it references class "App\\Entity\\Armoire" but no such service exists.'],
        ], [
            'armoire' => 'App\\Entity\\Armoire',
        ]);
    }
}
