<?php

namespace ContainerQLMY1N5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1miJ0OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f1miJ0O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f1miJ0O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PagesController::editArmoire' => ['privates', '.service_locator.Dx.TSUV', 'get_ServiceLocator_Dx_TSUVService', true],
            'App\\Controller\\PagesController::listarmoire' => ['privates', '.service_locator.7m5G278', 'get_ServiceLocator_7m5G278Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\PagesController:editArmoire' => ['privates', '.service_locator.Dx.TSUV', 'get_ServiceLocator_Dx_TSUVService', true],
            'App\\Controller\\PagesController:listarmoire' => ['privates', '.service_locator.7m5G278', 'get_ServiceLocator_7m5G278Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\PagesController::editArmoire' => '?',
            'App\\Controller\\PagesController::listarmoire' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PagesController:editArmoire' => '?',
            'App\\Controller\\PagesController:listarmoire' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
