<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGXAtxQo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGXAtxQo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGXAtxQo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGXAtxQo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGXAtxQo\App_KernelDevDebugContainer([
    'container.build_hash' => 'GXAtxQo',
    'container.build_id' => '83f75fa1',
    'container.build_time' => 1692890513,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGXAtxQo');
