<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27xqpof\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27xqpof/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container27xqpof.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container27xqpof\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container27xqpof\App_KernelDevDebugContainer([
    'container.build_hash' => '27xqpof',
    'container.build_id' => '1c55cfca',
    'container.build_time' => 1692621743,
], __DIR__.\DIRECTORY_SEPARATOR.'Container27xqpof');
