<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9rQkzYl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9rQkzYl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9rQkzYl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9rQkzYl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9rQkzYl\App_KernelDevDebugContainer([
    'container.build_hash' => '9rQkzYl',
    'container.build_id' => '961cd94b',
    'container.build_time' => 1691705072,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9rQkzYl');
